;;; cm-ai-registry-tests.el --- Tests for cm-ai-registry  -*- lexical-binding: t; -*-
;;; Code:
(require 'ert)
(require 'cm-ai-registry)

(ert-deftest cm/ai-registry-descriptor-has-core-fields ()
  (let* ((server-name "emacs-4242")
         (default-directory temporary-file-directory)
         (d (cm/ai-registry-descriptor)))
    (should (equal (alist-get 'server_name d) "emacs-4242"))
    (should (equal (alist-get 'pid d) (emacs-pid)))
    (should (stringp (alist-get 'project_root d)))
    (should (string-suffix-p "/" (alist-get 'project_root d)))))

(ert-deftest cm/ai-registry-write-read-roundtrip ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (desc '((project_root . "/home/jim/projects/emacs-again/")
                 (server_name . "emacs-4242") (pid . 4242)
                 (socket . "/run/user/1000/emacs/emacs-4242")
                 (frame_title . "x") (started . "2026-08-28T20:00:00+0000")))
         (file (cm/ai-registry--write desc dir))
         (got (cm/ai-registry--read file)))
    (should (equal file (expand-file-name "emacs-4242.json" dir)))
    (should (equal (plist-get got :project_root) "/home/jim/projects/emacs-again/"))
    (should (equal (plist-get got :pid) 4242))
    (should (member file (cm/ai-registry--files* dir)))))

(ert-deftest cm/ai-registry-sweep-drops-dead-keeps-live ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (live-pred (lambda (pid) (= pid 1)))) ; only pid 1 is "live"
    (cm/ai-registry--write '((server_name . "emacs-1") (pid . 1)
                             (project_root . "/a/")) dir)
    (cm/ai-registry--write '((server_name . "emacs-2") (pid . 2)
                             (project_root . "/b/")) dir)
    (cm/ai-registry--sweep dir live-pred)
    (should (file-exists-p (expand-file-name "emacs-1.json" dir)))
    (should-not (file-exists-p (expand-file-name "emacs-2.json" dir)))))

(ert-deftest cm/ai-registry-register-and-deregister ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (cm/ai-registry-dir dir)
         (server-name (format "emacs-%d" (emacs-pid)))
         (default-directory temporary-file-directory)
         (kill-emacs-hook nil))
    (cm/ai-registry-register)
    (should (file-exists-p (cm/ai-registry--file)))
    (should (memq #'cm/ai-registry-deregister kill-emacs-hook))
    (cm/ai-registry-deregister)
    (should-not (file-exists-p (cm/ai-registry--file)))))

(ert-deftest cm/ai-registry-resolve-most-specific-then-newest ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (cm/ai-registry-dir dir)
         (all-live (lambda (_pid) t)))
    ;; broad root, older
    (cm/ai-registry--write '((server_name . "emacs-10") (pid . 10)
                             (project_root . "/home/jim/projects/")
                             (started . "2026-08-28T10:00:00+0000")) dir)
    ;; specific root, older
    (cm/ai-registry--write '((server_name . "emacs-11") (pid . 11)
                             (project_root . "/home/jim/projects/app/")
                             (started . "2026-08-28T10:00:00+0000")) dir)
    ;; specific root, newer -> should win on tie of specificity
    (cm/ai-registry--write '((server_name . "emacs-12") (pid . 12)
                             (project_root . "/home/jim/projects/app/")
                             (started . "2026-08-28T20:00:00+0000")) dir)
    (should (equal (cm/ai-registry-resolve "/home/jim/projects/app/sub/deep" all-live)
                   "emacs-12"))
    ;; a cwd only the broad root covers
    (should (equal (cm/ai-registry-resolve "/home/jim/projects/other/x" all-live)
                   "emacs-10"))))

(ert-deftest cm/ai-registry-resolve-filters-dead-and-nonmatching ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (cm/ai-registry-dir dir)
         (only-13-live (lambda (pid) (= pid 13))))
    (cm/ai-registry--write '((server_name . "emacs-13") (pid . 13)
                             (project_root . "/home/jim/projects/app/")
                             (started . "2026-08-28T10:00:00+0000")) dir)
    (cm/ai-registry--write '((server_name . "emacs-14") (pid . 14)
                             (project_root . "/home/jim/projects/app/")
                             (started . "2026-08-28T20:00:00+0000")) dir)
    ;; newer 14 is dead -> live 13 wins despite older
    (should (equal (cm/ai-registry-resolve "/home/jim/projects/app/x" only-13-live)
                   "emacs-13"))
    ;; cwd outside every project_root -> nil
    (should-not (cm/ai-registry-resolve "/tmp/unrelated" only-13-live))))

(ert-deftest cm/ai-registry-resolve-skips-malformed-descriptor ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (cm/ai-registry-dir dir)
         (all-live (lambda (_pid) t))
         (bad-file (expand-file-name "emacs-bad.json" dir)))
    ;; A malformed/half-written descriptor sits alongside a valid one — the
    ;; concurrency contract is that a bad file is skipped, not fatal.
    (with-temp-file bad-file (insert "{ not json"))
    (cm/ai-registry--write '((server_name . "emacs-20") (pid . 20)
                             (project_root . "/home/jim/projects/app/")
                             (started . "2026-08-28T10:00:00+0000")) dir)
    (should-not (cm/ai-registry--read bad-file))
    (should (equal (cm/ai-registry-resolve "/home/jim/projects/app/x" all-live)
                   "emacs-20"))))

(provide 'cm-ai-registry-tests)
;;; cm-ai-registry-tests.el ends here
