;;; cm-ai-registry-tests.el --- Tests for cm-ai-registry  -*- lexical-binding: t; -*-
;;; Code:
(require 'ert)
(require 'cm-ai-registry)

(ert-deftest cm/ai-registry-descriptor-has-core-fields ()
  (let* ((server-name "emacs-4242")
         (default-directory temporary-file-directory)
         (d (cm/ai-registry-descriptor)))
    (should (equal (alist-get 'server_name d) "emacs-4242"))
    (should (equal (alist-get 'pid d) (emacs-pid)))
    (should (stringp (alist-get 'project_root d)))
    (should (string-suffix-p "/" (alist-get 'project_root d)))))

(ert-deftest cm/ai-registry-write-read-roundtrip ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (desc '((project_root . "/home/jim/projects/emacs-again/")
                 (server_name . "emacs-4242") (pid . 4242)
                 (socket . "/run/user/1000/emacs/emacs-4242")
                 (frame_title . "x") (started . "2026-08-28T20:00:00+0000")))
         (file (cm/ai-registry--write desc dir))
         (got (cm/ai-registry--read file)))
    (should (equal file (expand-file-name "emacs-4242.json" dir)))
    (should (equal (plist-get got :project_root) "/home/jim/projects/emacs-again/"))
    (should (equal (plist-get got :pid) 4242))
    (should (member file (cm/ai-registry--files* dir)))))

(ert-deftest cm/ai-registry-sweep-drops-dead-keeps-live ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (live-pred (lambda (pid) (= pid 1)))) ; only pid 1 is "live"
    (cm/ai-registry--write '((server_name . "emacs-1") (pid . 1)
                             (project_root . "/a/")) dir)
    (cm/ai-registry--write '((server_name . "emacs-2") (pid . 2)
                             (project_root . "/b/")) dir)
    (cm/ai-registry--sweep dir live-pred)
    (should (file-exists-p (expand-file-name "emacs-1.json" dir)))
    (should-not (file-exists-p (expand-file-name "emacs-2.json" dir)))))

(ert-deftest cm/ai-registry-register-and-deregister ()
  (let* ((dir (file-name-as-directory (make-temp-file "cmair" t)))
         (cm/ai-registry-dir dir)
         (server-name (format "emacs-%d" (emacs-pid)))
         (default-directory temporary-file-directory)
         (kill-emacs-hook nil))
    (cm/ai-registry-register)
    (should (file-exists-p (cm/ai-registry--file)))
    (should (memq #'cm/ai-registry-deregister kill-emacs-hook))
    (cm/ai-registry-deregister)
    (should-not (file-exists-p (cm/ai-registry--file)))))

(provide 'cm-ai-registry-tests)
;;; cm-ai-registry-tests.el ends here
